document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
  const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
  if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));}
  const lectures=[
    ['JEE ADVANCED','JEE Advanced Physics Paper Solution','Detailed solution and reasoning for advanced physics problems.','https://www.youtube.com/live/3TT1crLy9PQ?si=gyVhZIM5InkcNF4o'],
    ['JEE MAINS','JEE Mains Physics Paper Solution','Work through the paper and understand each answer.','https://www.youtube.com/live/3IbsP-95MRE?si=BYujEr7TzCAeNRiB'],
    ['NEET','NEET Physics Paper Solution','A clear, step-by-step paper discussion.','https://www.youtube.com/live/Ya75UNbuVaI?si=JN63seRXFpHVkw8d'],
    ['MECHANICS',"Newton's Law of Motion",'See how force, motion and mechanics fit together.','https://www.youtube.com/live/ARLQwOAdqd0?si=HOgtkaaQIqB0UaC2'],
    ['ROTATIONAL MOTION','Angular Momentum','Explore rotational motion through intuition and equations.','https://youtu.be/iGLd6pqGu4w?si=UUK1ZToThHkY8fD_'],
    ['OPTICS','Refraction of Light','Understand why light bends between materials.','https://youtu.be/dD5CMx5GeSM?si=uSyKlizkeR7II3kT'],
    ['CBSE CLASS 12','CBSE 12th Physics PYQ','Practice previous-year questions concept-first.','https://www.youtube.com/live/FvA6a8dzL0o?si=KaM5WR5qZ9bzRz5C'],
    ['BIHAR BOARD','Bihar Board 12th PYQ','Prepare with guided previous-year solutions.','https://www.youtube.com/live/3RmLjiBsL1Q?si=8xGlEimTatNyZGV0'],
    ['NCERT','NCERT Clear','Make NCERT concepts clear and connected.','https://www.youtube.com/live/fpqUMPcvvmc?si=3dFFE43w-sMJs3x9']
  ];
  const playlists=[
    ['JEE ADVANCED','JEE Advanced Paper Solution','https://youtube.com/playlist?list=PLjEkQ_dvlIGmJCQv5QKkfGWBBCLtzgQr1&si=I7vTInci3mQOs9N2'],['NEET','NEET Exam Paper Solution','https://youtube.com/playlist?list=PLjEkQ_dvlIGm7bdSxNp61GfEgAgpcb7c3&si=EcrB9UqsoHXF4uZG'],['CLASS 12','12th DEEP Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGmz5Nu8Eo3tbW7C6TWxg47M&si=w7Tp_LEO3NaNfjpT'],['CLASS 11','11th Morning Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGnJopwUTNwm4zB88Stdj8sc&si=HwBloKVuYDkOz8OG'],['CLASS 11','11th Deep Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGkgKaiK8vYlJZRkklOYwrZ8&si=hmjmuwMQQu10lkGX'],['SERIES','Evening Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGm5vX6_yZjSzkwPIv5BOr7d&si=ZVGB_tkm3_Lu_-vY'],['REVISION','Quick Revision: System of Particles','https://youtube.com/playlist?list=PLjEkQ_dvlIGldL1j2dvWCqR-9J_d1rQTv&si=5iBtkozfmJv2Pw53'],['STRATEGY',"Topper's Strategy",'https://youtube.com/playlist?list=PLjEkQ_dvlIGlbjHCLVfFG1LOmz6DhCpOB&si=YqUhwj7uVVRb-o9a'],['JEE','Clear JEE Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGnUR6SCSdM0oApUY7jldn1R&si=oW1Z8Fck_6wSgLFZ'],['NEET','Clear NEET Physics','https://youtube.com/playlist?list=PLjEkQ_dvlIGnoVXe4df8IAa1Ka-wvy9qr&si=jX-Sus6vzYBF-GnI'],['CLASS 10','10th Quick Revision','https://youtube.com/playlist?list=PLjEkQ_dvlIGnrLTOGX75hlPRQE2mMDkUT&si=0ppHTD3-aq98uUrV'],['CLASS 9','9th Quick Revision','https://youtube.com/playlist?list=PLjEkQ_dvlIGk-Y6nr-ldTnnCr8uRftGiC&si=9ygXAY1V3050SBG5'],['CBSE','CBSE 12th Board Exam','https://youtube.com/playlist?list=PLjEkQ_dvlIGlHZ0f8U3R3_i1t9YFURQex&si=J-_FE2Sh3OdO0_aR'],['BIHAR BOARD','Bihar Board Exam Guess','https://youtube.com/playlist?list=PLjEkQ_dvlIGk0GPyRclNXoJYx7kQ5OQLV&si=aBSlHE8EMinmehJV']
  ];
  const topics=[['MECHANICS','NCERT Questions: Laws of Motion','Motion, forces and the logic behind acceleration.','https://youtube.com/playlist?list=PLjEkQ_dvlIGmj-GBjRI7WC_vzYn4-7Si5&si=hqmCPs2kr-OM5-mF'],['MATHEMATICAL TOOLS','NCERT Book: Units, Dimensions & Errors','The language of measurement and physical reasoning.','https://youtube.com/playlist?list=PLjEkQ_dvlIGk-_9QojNMbg6vhRrk1C0Yg&si=YWpAnwJcX90NDFev'],['PROBLEM SOLVING','Work, Energy & Power','Question-first problem solving with the right intuition.','https://www.youtube.com/live/94KWCWIpTWM?si=GXJzfDrZw8iYHCC8'],['QUICK REVISION','Electrostatics','Electric fields, force and central ideas in one pass.','https://youtu.be/OzuS2LwJwzI?si=531yUfZV0wWUEuSS'],['QUICK REVISION','Gravitation','Gravity, orbits and central forces.','https://youtube.com/playlist?list=PLjEkQ_dvlIGlDLayMTKe7kAf28RswrXAc&si=aWb3DhyKGrZKYCxZ'],['MODERN PHYSICS','Modern Physics','The world beyond classical intuition.','https://youtube.com/playlist?list=PLjEkQ_dvlIGmYGbJoXdyKCa3eN6w0OrL0&si=FMKiyUA__LxuaSLx']];
  function card([tag,title,description,url]){const a=document.createElement('a');a.className='resource-card';a.href=url;a.target='_blank';a.rel='noopener';a.innerHTML=`<span class="tag">${tag}</span><h3>${title}</h3><p>${description}</p>`;return a}
  const lectureGrid=document.getElementById('lecture-grid'),playlistGrid=document.getElementById('playlist-grid'),topicGrid=document.getElementById('topic-grid');
  if(lectureGrid)lectures.forEach(x=>lectureGrid.appendChild(card(x)));
  if(playlistGrid)playlists.forEach(x=>playlistGrid.appendChild(card([...x,'Browse this learning path.'])));
  if(topicGrid)topics.forEach(([tag,title,desc,url],i)=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.innerHTML=`<span>0${i+1}</span><strong>${title}</strong><small>${tag} · ${desc}</small><b>↗</b>`;topicGrid.appendChild(a)});
  const canvas=document.getElementById('orbit-canvas');
  if(canvas){const ctx=canvas.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2);let w,h,t=0;function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}function draw(){ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2,h/2);[.25,.38,.51,.64,.77].forEach((s,i)=>{ctx.beginPath();ctx.ellipse(0,0,w*s,h*s*.52,(i-.5)*.35,0,Math.PI*2);ctx.strokeStyle=`rgba(241,244,238,${.13-i*.016})`;ctx.stroke()});const x=Math.cos(t)*w*.31,y=Math.sin(t)*h*.18;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(x,y);ctx.strokeStyle='rgba(115,215,245,.35)';ctx.stroke();ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fillStyle='#f3cc6a';ctx.fill();ctx.beginPath();ctx.arc(0,0,12+Math.sin(t*2)*2,0,Math.PI*2);ctx.fillStyle='#73d7f5';ctx.fill();ctx.restore();t+=.008;requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw()}
});